#!/usr/bin/env python
"""
OrBlink by Hadley Rich <hads@nice.net.nz>

Copyright (c) <2013>, <hads@nice.net.nz>
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import os, sys
try:
  import webcolors
except ImportError:
  webcolors = None

from orblink import *

if __name__ == '__main__':

  orb = OrBlink(vendor_id=0x16c0, product_id=0x05df)
  if not orb.valid:
    sys.stderr.write("Couldn't find OrBlink device.\n")
    sys.exit(1)

  if len(sys.argv) == 2:
    if sys.argv[1] == 'store':
      orb.store()
      sys.exit(2)
    if not webcolors:
      sys.stderr.write("Named and hex colors require the 'webcolors' module.\n")
      sys.exit(2)
    if sys.argv[1].startswith('#'):
      try:
        r, g, b = webcolors.hex_to_rgb(sys.argv[1])
      except ValueError:
        sys.stderr.write("Couldn't work out hex color.\n")
        sys.exit(2)
    else:
      try:
        r, g, b = webcolors.name_to_rgb(sys.argv[1])
      except ValueError:
        sys.stderr.write("Couldn't work out named color.\n")
        sys.exit(2)
    orb.set_color(r, g, b)
  elif len(sys.argv) == 4:
    try:
      r = int(sys.argv[1])
      g = int(sys.argv[2])
      b = int(sys.argv[3])
    except:
      sys.stderr.write("Couldn't work out RGB color.\n")
      sys.exit(2)
    orb.set_color(r, g, b)

